"""
HodgeRank D2 pipeline for perceptual triplet data.

Reads the pre-computed agreement scores from `testset1_triplet_entropy.csv`
(generated by perm.ipynb), builds the D2 boundary operator (triangles -> edges)
as a standard signed incidence matrix, computes edge similarity weights and
per-node oddness-consistency statistics, and exports everything to data.json
for the D3.js visualization.

Run with:  python3.12 hodgerank.py

Author: Utkarsh Raj Sutihar
"""

import json
import math
from pathlib import Path

import numpy as np
import pandas as pd
from scipy.sparse import csc_matrix, save_npz
from scipy.sparse.linalg import lsqr
from scipy.io import mmwrite

CSV_PATH = Path("output/testset1_triplet_entropy.csv")
JSON_OUT = Path("output/data.json")
D2_NPZ = Path("output/D2.npz")            # scipy sparse binary
D2_MTX = Path("output/D2.mtx")            # portable MatrixMarket text
EDGE_INDEX_CSV = Path("output/edge_index.csv")  # maps D2 row -> edge (node_a, node_b)
S1_CSV = Path("output/s1_star.csv")              # projection vector s^1_* (one value per edge)


# ---------------------------------------------------------------------------
# Step 1: Read pre-computed agreement scores
# ---------------------------------------------------------------------------
def load_triplets(csv_path=CSV_PATH):
    """Load canonical triplets with oddness probabilities and agreement scores.

    Each row of the CSV is a canonical triplet (i < j < k) with the odd-one-out
    percentages for each vertex (in [0, 100]) and a precomputed agreement score.
    Returns a DataFrame with probability columns p_i, p_j, p_k added.
    """
    df = pd.read_csv(csv_path)

    # Convert percentages to probabilities (sum to 1 per triplet).
    df["p_i"] = df["odd_i_pct"] / 100.0
    df["p_j"] = df["odd_j_pct"] / 100.0
    df["p_k"] = df["odd_k_pct"] / 100.0

    # Sanity check: probabilities sum to 1.
    prob_sums = df[["p_i", "p_j", "p_k"]].sum(axis=1)
    assert np.allclose(prob_sums, 1.0), "Oddness probabilities must sum to 1"

    # Sanity check: triplets are canonical (i < j < k).
    assert (df["i"] < df["j"]).all() and (df["j"] < df["k"]).all(), \
        "Triplets must be canonical (i < j < k)"

    return df


# ---------------------------------------------------------------------------
# Step 2: Build the D2 boundary operator (edges x triangles)
# ---------------------------------------------------------------------------
def build_indices(df):
    """Build contiguous node and edge indices from the triplet table.

    Returns:
        node_id_of_idx : list mapping contiguous node index -> original node ID
        node_idx_of_id : dict mapping original node ID -> contiguous index
        edge_list      : list of (a, b) tuples with a < b (original IDs),
                         indexed by contiguous edge ID
        edge_idx_of    : dict mapping (a, b) -> contiguous edge index
    """
    # Collect all distinct node IDs.
    node_ids = pd.unique(df[["i", "j", "k"]].values.ravel())
    node_ids = sorted(int(n) for n in node_ids)
    node_idx_of_id = {nid: idx for idx, nid in enumerate(node_ids)}

    # Collect all distinct edges. For triangle (i, j, k) with i<j<k the three
    # boundary edges are (i,j), (i,k), (j,k) -- all already a < b.
    edge_idx_of = {}
    edge_list = []
    for _, row in df.iterrows():
        i, j, k = int(row["i"]), int(row["j"]), int(row["k"])
        for a, b in ((i, j), (i, k), (j, k)):
            if (a, b) not in edge_idx_of:
                edge_idx_of[(a, b)] = len(edge_list)
                edge_list.append((a, b))

    return node_ids, node_idx_of_id, edge_list, edge_idx_of


def build_D2(df, edge_idx_of):
    """Build D2: the signed (edges x triangles) incidence matrix.

    For triangle t = (i, j, k) with i < j < k:
        D2[edge(i,j), t] = +1
        D2[edge(i,k), t] = -1
        D2[edge(j,k), t] = +1

    This matches the boundary formula in GenerateD2.m.
    """
    n_edges = len(edge_idx_of)
    n_triangles = len(df)

    rows, cols, vals = [], [], []
    for t, (_, row) in enumerate(df.iterrows()):
        i, j, k = int(row["i"]), int(row["j"]), int(row["k"])
        # (i,j) -> +1, (i,k) -> -1, (j,k) -> +1
        rows.append(edge_idx_of[(i, j)]); cols.append(t); vals.append(+1)
        rows.append(edge_idx_of[(i, k)]); cols.append(t); vals.append(-1)
        rows.append(edge_idx_of[(j, k)]); cols.append(t); vals.append(+1)

    D2 = csc_matrix((vals, (rows, cols)), shape=(n_edges, n_triangles))
    return D2


def build_D1(edge_list, node_idx_of_id):
    """Build D1: the signed (nodes x edges) incidence matrix.

    For edge e = (a, b) with a < b:
        D1[a, e] = +1
        D1[b, e] = -1

    Only needed to verify the boundary-of-boundary property D1 @ D2 == 0.
    Matches GenerateD1.m's orientation convention.
    """
    n_nodes = len(node_idx_of_id)
    n_edges = len(edge_list)

    rows, cols, vals = [], [], []
    for e, (a, b) in enumerate(edge_list):
        rows.append(node_idx_of_id[a]); cols.append(e); vals.append(+1)
        rows.append(node_idx_of_id[b]); cols.append(e); vals.append(-1)

    D1 = csc_matrix((vals, (rows, cols)), shape=(n_nodes, n_edges))
    return D1


def validate_D2(D2, D1):
    """Run the structural and topological checks on D2."""
    # Sparsity: exactly 3 nonzeros per column (each triangle has 3 edges).
    nnz_per_col = np.diff(D2.indptr)
    assert (nnz_per_col == 3).all(), "Every triangle column must have exactly 3 edges"

    # At most 2 nonzeros per row (an edge is shared by at most 2 triangles here).
    nnz_per_row = np.asarray((D2 != 0).sum(axis=1)).ravel()
    max_shared = int(nnz_per_row.max())

    # Values are all +/-1.
    assert set(np.unique(D2.data)).issubset({-1, 1}), "D2 entries must be +/-1"

    # Boundary of a boundary is zero: D1 @ D2 == 0.
    product = (D1 @ D2)
    max_abs = np.abs(product.toarray()).max() if product.nnz else 0
    assert max_abs == 0, f"D1 @ D2 must be the zero matrix (got max |entry| = {max_abs})"

    return {
        "nnz_per_col_all_3": True,
        "max_triangles_per_edge": max_shared,
        "n_shared_edges": int((nnz_per_row >= 2).sum()),
        "D1_D2_is_zero": True,
    }


# ---------------------------------------------------------------------------
# Step 3: Edge similarity weights
# ---------------------------------------------------------------------------
def compute_edge_weights(df, edge_list, edge_idx_of):
    """Compute edge similarity weights: sim(a,b) = P(third vertex is odd).

    For edge (a,b) in triangle (i,j,k), the third vertex is the one not in
    {a,b}, and sim(a,b) = P(that vertex is odd). For edges shared by two
    triangles, aggregate as a count-weighted average.
    """
    # Accumulate weighted sums and total counts per edge.
    weighted_sum = np.zeros(len(edge_list))
    total_count = np.zeros(len(edge_list))

    for _, row in df.iterrows():
        i, j, k = int(row["i"]), int(row["j"]), int(row["k"])
        n = row["total_count"]
        p_i, p_j, p_k = row["p_i"], row["p_j"], row["p_k"]

        # sim of the pair = P(the excluded third vertex is odd).
        for (a, b), sim in (((i, j), p_k), ((i, k), p_j), ((j, k), p_i)):
            e = edge_idx_of[(a, b)]
            weighted_sum[e] += n * sim
            total_count[e] += n

    similarity = weighted_sum / total_count
    return similarity


# ---------------------------------------------------------------------------
# Step 4: Per-node oddness-consistency analysis
# ---------------------------------------------------------------------------
def compute_node_stats(df):
    """For each node, collect P(odd) across its triangles and summarise.

    Returns a dict: node_id -> {mean_oddness, var_oddness, n_triangles, category}.
    """
    # node_id -> list of (P(node odd), total_count)
    oddness = {}

    for _, row in df.iterrows():
        for nid, p in ((int(row["i"]), row["p_i"]),
                       (int(row["j"]), row["p_j"]),
                       (int(row["k"]), row["p_k"])):
            oddness.setdefault(nid, []).append(p)

    stats = {}
    for nid, ps in oddness.items():
        ps = np.array(ps)
        mu = float(ps.mean())
        var = float(ps.var())  # population variance
        n_tri = len(ps)

        if n_tri > 1 and var > 0.1:
            category = "context_dependent"
        elif mu > 0.5 and var < 0.05:
            category = "consistently_odd"
        elif mu < 0.2 and var < 0.05:
            category = "consistently_similar"
        else:
            category = "mixed"

        stats[nid] = {
            "mean_oddness": mu,
            "var_oddness": var,
            "n_triangles": n_tri,
            "category": category,
        }

    return stats


# ---------------------------------------------------------------------------
# Step 5: Hodge projection  s^1_* = pinv(D2 D2^T) D2 s^2
#   Equivalent to lsqr(D2^T, s^2) — same minimum-norm least-squares solution,
#   computed iteratively without forming the dense Laplacian D2 D2^T.
# ---------------------------------------------------------------------------
def hodge_project(D2, df):
    """Project the triangle data s^2 onto edges via the Hodge equation.

    s^2 = agreement score per triangle (length n_triangles).
    s^1_* = pinv(D2 D2^T) D2 s^2  =  pinv(D2^T) s^2  (length n_edges).

    Returns:
        s1_star      : 1d array (n_edges,) — the projection vector s^1_*
        s2_hat       : 1d array (n_triangles,) — reconstructed s^2_hat = D2^T s^1_*
        residual     : 1d array (n_triangles,) — s^2 - s^2_hat (higher-order part)
        frac_explained : float — ||s^2_hat||^2 / ||s^2||^2
    """
    s2 = df["agreement_score"].values.astype(np.float64)

    result = lsqr(D2.T, s2)
    s1_star = result[0]

    s2_hat = D2.T @ s1_star
    residual = s2 - s2_hat

    norm_s2_sq = np.dot(s2, s2)
    norm_hat_sq = np.dot(s2_hat, s2_hat)
    frac_explained = norm_hat_sq / norm_s2_sq if norm_s2_sq > 0 else 0.0

    return s1_star, s2_hat, residual, frac_explained


def export_s1(s1_star, edge_list, path=S1_CSV):
    """Write the projection vector s^1_* as a CSV."""
    with path.open("w", encoding="utf-8") as f:
        f.write("edge_id,node_a,node_b,s1_star\n")
        for e, (a, b) in enumerate(edge_list):
            f.write(f"{e},{a},{b},{s1_star[e]:.8f}\n")


# ---------------------------------------------------------------------------
# Export the D2 operator as a sparse matrix (+ interpretable indices)
# ---------------------------------------------------------------------------
def export_D2(D2, edge_list, similarity, df):
    """Persist D2 in two sparse formats plus an edge-index lookup.

    - D2.npz : scipy sparse (load with scipy.sparse.load_npz)
    - D2.mtx : MatrixMarket text (portable: MATLAB/Octave/Julia/etc.)
    - edge_index.csv : row index -> (node_a, node_b, similarity)
      Columns of D2 follow the triplet order of the input CSV
      (column t corresponds to triplet row t: i, j, k).
    """
    save_npz(D2_NPZ, D2)
    mmwrite(str(D2_MTX), D2, comment=(
        "D2 boundary operator (edges x triangles). "
        "Column t = triplet (i,j,k); rows are edges per edge_index.csv. "
        "Triangle (i<j<k): edge(i,j)->+1, edge(i,k)->-1, edge(j,k)->+1."
    ), field="integer")

    with EDGE_INDEX_CSV.open("w", encoding="utf-8") as f:
        f.write("edge_id,node_a,node_b,similarity\n")
        for e, (a, b) in enumerate(edge_list):
            f.write(f"{e},{a},{b},{similarity[e]:.6f}\n")


# ---------------------------------------------------------------------------
# Step 5: Export JSON for the D3 visualization
# ---------------------------------------------------------------------------
def export_json(df, node_ids, edge_list, similarity, node_stats, path=JSON_OUT):
    """Write nodes, edges, and triangles to a single JSON file for D3."""
    nodes = []
    for nid in node_ids:
        s = node_stats[nid]
        nodes.append({
            "id": nid,
            "mean_oddness": round(s["mean_oddness"], 4),
            "var_oddness": round(s["var_oddness"], 4),
            "n_triangles": s["n_triangles"],
            "category": s["category"],
        })

    edges = []
    for e, (a, b) in enumerate(edge_list):
        edges.append({
            "source": a,
            "target": b,
            "similarity": round(float(similarity[e]), 4),
        })

    triangles = []
    for _, row in df.iterrows():
        triangles.append({
            "i": int(row["i"]), "j": int(row["j"]), "k": int(row["k"]),
            "p_i": round(row["p_i"], 4),
            "p_j": round(row["p_j"], 4),
            "p_k": round(row["p_k"], 4),
            "agreement": round(float(row["agreement_score"]), 4),
            "total_count": int(row["total_count"]),
        })

    payload = {"nodes": nodes, "edges": edges, "triangles": triangles}
    with path.open("w", encoding="utf-8") as f:
        json.dump(payload, f)

    return payload


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main():
    print("Loading triplets ...")
    df = load_triplets()
    print(f"  {len(df):,} canonical triplets")

    print("Building indices ...")
    node_ids, node_idx_of_id, edge_list, edge_idx_of = build_indices(df)
    print(f"  {len(node_ids):,} nodes, {len(edge_list):,} edges")

    print("Building D2 (edges x triangles) ...")
    D2 = build_D2(df, edge_idx_of)
    print(f"  D2 shape = {D2.shape}, nnz = {D2.nnz}")

    print("Building D1 (nodes x edges) for validation ...")
    D1 = build_D1(edge_list, node_idx_of_id)

    print("Validating D2 ...")
    checks = validate_D2(D2, D1)
    for key, val in checks.items():
        print(f"  {key}: {val}")

    print("Computing edge similarity weights ...")
    similarity = compute_edge_weights(df, edge_list, edge_idx_of)
    # Verify the 3 weights per triangle sum to 1.
    sample = df.iloc[0]
    s_ij = similarity[edge_idx_of[(int(sample.i), int(sample.j))]]
    s_ik = similarity[edge_idx_of[(int(sample.i), int(sample.k))]]
    s_jk = similarity[edge_idx_of[(int(sample.j), int(sample.k))]]
    print(f"  similarity range [{similarity.min():.3f}, {similarity.max():.3f}]")
    print(f"  sample triangle edge-weight sum = {s_ij + s_ik + s_jk:.4f} (expect ~1.0)")

    print("Computing per-node oddness statistics ...")
    node_stats = compute_node_stats(df)
    from collections import Counter
    cat_counts = Counter(s["category"] for s in node_stats.values())
    for cat, cnt in cat_counts.most_common():
        print(f"  {cat}: {cnt}")

    print("Hodge projection: s^1_* = pinv(D2 D2^T) D2 s^2  (s^2 = agreement) ...")
    s1_star, s2_hat, residual, frac = hodge_project(D2, df)
    print(f"  s1_star shape = ({len(s1_star)},)  (one value per edge)")
    print(f"  s1_star range = [{s1_star.min():.6f}, {s1_star.max():.6f}]")
    print(f"  ||residual|| / ||s2|| = {np.linalg.norm(residual) / np.linalg.norm(df['agreement_score'].values):.6f}")
    print(f"  fraction explained by edges = {frac:.6f}  ({frac*100:.2f}%)")

    print("Exporting s1_star.csv ...")
    export_s1(s1_star, edge_list)
    print(f"  wrote {S1_CSV}")

    print("Exporting D2 sparse matrix ...")
    export_D2(D2, edge_list, similarity, df)
    print(f"  wrote {D2_NPZ}, {D2_MTX}, {EDGE_INDEX_CSV}")

    print("Exporting data.json ...")
    payload = export_json(df, node_ids, edge_list, similarity, node_stats)
    print(f"  wrote {JSON_OUT} "
          f"({len(payload['nodes'])} nodes, {len(payload['edges'])} edges, "
          f"{len(payload['triangles'])} triangles)")

    print("Done.")


if __name__ == "__main__":
    main()
